config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  
  get 'dashboard/update'

  resources :users
  resources :tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  has_many :tweets

  enum status: [:success, :failed]

  def update_tweets

    result = TweetService.pull
    count_keywords = 0

    if result.present?
      result.each do |tweet_obj|
        user = User.find_or_create_by(id: tweet_obj.id)
        user.update(username: tweet_obj.user_handle, followers: tweet_obj.followers)

        tweet = Tweet.find_or_create_by(created_at: tweet_obj.created_at)
        tweet.update(user: user, message: tweet_obj.message, sentiment: tweet_obj.sentiment_float, keyword: tweet_obj.keyword, record: self)

        count_keywords += 1 if tweet_obj.keyword
      end

      self.update(total_tweets: result.count, total_keywords: count_keywords)
      self.success!
    else
      self.failed!
    end
  end

  def keyword_percent
    (total_keywords.to_f / total_tweets.to_f)*100
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :record

  scope :with_keywords, -> { where(keyword: true)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, dependent: :destroy

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @last_record = Record.last || Record.new
  end

  def update

    record = Record.create

    record.update_tweets

    if (record.success?)
      redirect_to root_path, notice: 'Tweets have been updated successfully.'
    else
      redirect_to root_path, alert: 'Tweets have not been updated. Something happened! :('
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    # binding.pry
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :sentiment, :user_id, :record_id, :keyword)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :followers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_tweet.html.erb
<tr>
  <td><%= tweet.id %></td>
  <td><%= tweet.message %></td>
  <td><%= button_to 'Show', tweet_path(tweet), method: :get, class: "btn btn-outline-secondary" %></td>
</tr>

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h1">Dashboard</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= button_to "Pull new Tweets", dashboard_update_path, method: :get,  class: "btn btn-sm btn-outline-secondary" %>
  </div>
</div>

<h4 class="mt-5">Resume of last update</h4>
<div class="row">
  <div class="col-sm-12">
    <div class="card bg-light mb-3">
      <div class="card-body">
        <strong>Status:</strong> <span class="status-<%= @last_record.status %>"><%= @last_record.status %></span> -
        <strong>Date:</strong> <%= @last_record.created_at %>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card bg-light mb-3">
      <div class="card-header">Keyword Percent</div>
      <div class="card-body">
        <h3 class="card-title text-center"><%= number_to_percentage(@last_record.keyword_percent, precision: 2) %></h3>
        <p class="card-text text-center">Percent of tweets with keywords</p>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
      <div class="card bg-light mb-3">
        <div class="card-header">Total Tweets</div>
        <div class="card-body">
          <h3 class="card-title text-center"><%= @last_record.total_tweets %></h3>
          <p class="card-text text-center">Number of tweets pulled</p>
        </div>
      </div>
  </div>
  <div class="col-sm-4">
      <div class="card bg-light mb-3">
        <div class="card-header">Total Keyword's Tweets</div>
        <div class="card-body">
          <h3 class="card-title text-center"><%= @last_record.total_keywords %></h3>
          <p class="card-text text-center">Number of tweets with keywords</p>
        </div>
      </div>
  </div>
</div>

<h4 class="mt-5">Tweets pulled</h4>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Message</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'tweet', collection: @last_record.tweets.with_keywords %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetsReport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container-fluid">
        <%= render "shared/aside" %>
        <div class="row">
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
            <%= yield %>
          </main>
      </div>
    </div>
  </body>
</html>

app/views/shared/_aside.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "Dashboard", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Tweets Report</a>

  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="field">
    <%= form.label :sentiment %>
    <%= form.text_field :sentiment %>
  </div>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.select :keyword  do %>
      <%= options_for_select([["Yes", true], ["No", false]]) %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id  do %>
      <%= options_for_select(User.all.map { |u| [u.username, u.id]}) %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h1">Tweets</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%#= link_to 'New Tweet', new_tweet_path, class: "btn btn-sm btn-outline-secondary" %>
  </div>
</div>

<table class="table table-striped mt-4">
  <thead>
    <tr>
      <th>Message</th>
      <th>Sentiment</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.sentiment %></td>
        <td><%= tweet.user %></td>
        <td><%= link_to 'Show', tweet, class: 'btn btn-outline-secondary' %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet), class: 'btn btn-outline-secondary' %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-secondary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>Sentiment:</strong>
  <%= @tweet.sentiment %>
</p>


<p>
  <strong>Followers:</strong>
  <%= @tweet.user.followers %>
</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :followers %>
    <%= form.number_field :followers %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h1">Users</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'New User', new_user_path, class: "btn btn-sm btn-outline-secondary" %>
  </div>
</div>

<table class="table table-striped mt-4">
  <thead>
    <tr>
      <th>Username</th>
      <th>Followers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.followers %></td>
        <td><%= link_to 'Show', user, class: 'btn btn-outline-secondary' %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-outline-secondary' %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-secondary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Followers:</strong>
  <%= @user.followers %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>